---
- name: Configure nginx LB
  hosts: app-test-lb
  gather_facts: fasle
  vars:
    web_server: "{{ newip }}:80"

  tasks:
  - name: add firewall port
    firewalld:
      port: 80/tcp
      permanent: true
      state: enabled
    notify:
    - restart firewalld

  - name: install config file
    template:
      src: app-test-nginx-lb.conf.j2
      dest: /etc/nginx/nginx.conf
    notify:
    - restart nginx

  handlers:
  - name: restart nginx
    service:
      name: nginx
      state: restarted
      enabled: yes

  - name: restart firewalld
    service:
      name: firewalld
      state: restarted
      enabled: yes
